---
- name: "Create user"
  user:
    name: "web"
    groups: "nginx,wheel"
    generate_ssh_key: "True"
    shell: "/bin/bash"

- name: "Copy .bashrc file"
  copy:
    src: "{{ role_path }}/files/bashrc"
    dest: /home/web/.bashrc
    owner: web
    group: web
    mode: '0644'

- name: "Copy .gitconfig file"
  copy:
    src: "{{ role_path }}/files/gitconfig"
    dest: /home/web/.gitconfig
    owner: web
    group: web
    mode: '0644'

- name: "Copy .my.cnf file"
  copy:
    src: "{{ role_path }}/files/my.cnf"
    dest: /home/web/.my.cnf
    owner: web
    group: web
    mode: '0644'
