
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node"
    scrape_interval: "15s"
    file_sd_configs:
      - files:
        - '/opt/stat/etc/prometheus/node.enabled/*.json'
#        - '/var/lib/prometheus/discovery/node/*.json'
