# roles/iptables/tasks/1-install.yml
---

- name: Check if Firewalld Exists
  shell: "if systemctl list-unit-files | grep -q firewalld; then echo 1; else echo 0; fi;"
  register: firewalld_exists
  tags: iptables

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: "firewalld_exists == 1"
  tags: iptables

- name: Remove firewalld
  yum:
    name: firewalld
    state: absent
    update_cache: yes
  tags: iptables

- name: Install iptables
  yum:
    name: iptables-services
    state: present
    update_cache: yes
  tags: iptables
