# roles/php-fpm73/tasks/1-install.yml
---

- name: Install PHP 7.3
  yum:
    name:
      - php73
      - php73-php
      - php73-php-fpm
      - php73-php-pdo
      - php73-php-pgsql
      - php73-php-mysqlnd
      - php73-php-bcmath
      - php73-php-cli
      - php73-php-common
      - php73-php-gd
      - php73-php-json
      - php73-php-mbstring
      - php73-php-mcrypt
      - php73-php-pecl-imagick
      - php73-php-pecl-redis
      - php73-php-xml
      - php73-php-devel
      - php73-php-opcache
      - php73-php-pecl-geoip
    state: present
  tags: php73

- name: Enable PHP 7.3 fpm service
  service:
    name: php73-php-fpm
    state: started
    enabled: yes
  tags: php73

- name: Create a php symbolic link
  file:
    src: /usr/bin/php73
    dest: /usr/bin/php
    state: link
  tags: php73





