# roles/php-fpm73/tasks/3-configs.yml
---

- name: Update config php.ini
  template:
    src: php.ini.j2
    dest: /etc/opt/remi/php73/php.ini
    owner: root
    group: root
    mode:  0644
  notify: restart php-fpm
  tags: php73

- name: Update config www.conf
  template:
    src: www.conf.j2
    dest: /etc/opt/remi/php73/php-fpm.d/www.conf
    owner: root
    group: root
    mode:  0644
  notify: restart php-fpm
  tags: php73

- name: Update config opcache.ini
  template:
    src: php.d/10-opcache.ini.j2
    dest: /etc/opt/remi/php73/php.d/10-opcache.ini
    owner: root
    group: root
    mode:  0644
  notify: restart php-fpm
  tags: php73






