---
- name: Install PHP 7.3
  yum:
    name:
      - php73
      - php73-php
      - php73-php-fpm
      - php73-php-pdo
      - php73-php-pgsql
      - php73-php-mysqlnd
      - php73-php-bcmath
      - php73-php-cli
      - php73-php-common
      - php73-php-gd
      - php73-php-json
      - php73-php-mbstring
      - php73-php-mcrypt
      - php73-php-pecl-imagick
      - php73-php-pecl-redis
      - php73-php-xml
      - php73-php-devel
      - php73-php-opcache
    state: present
  tags: php73

- name: Enable PHP 7.3 fpm service
  service:
    name: php73-php-fpm
    state: started
    enabled: yes
  tags: php73

- name: Create a php symbolic link
  file:
    src: /usr/bin/php73
    dest: /usr/bin/php
    state: link
  tags: php73

- name: Install policycoreutils
  yum:
    name:
      - policycoreutils
      - policycoreutils-devel
    state: present

- name: Enable semanage php-fpm port
  seport:
    ports: 9073
    proto: tcp
    setype: http_port_t
    state: present
  tags: php73

- name: Php-fpm www.conf
  template:
    src: www.conf.j2
    dest: /etc/opt/remi/php73/php-fpm.d/www.conf
    owner: root
    group: root
    mode:  0644
  notify: restart php-fpm
  tags: php73








