# roles/stat/tasks/2-prometheus-files.yml
---

# Configs

- name: "Creating /opt/stat/etc/prometheus/node.enabled"
  file:
    recurse: yes
    path: /opt/stat/etc/prometheus/node.enabled
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

- name: Creating /opt/stat/etc/prometheus/node.available
  file:
    recurse: yes
    path: /opt/stat/etc/prometheus/node.available
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

- name: Creating /opt/stat/etc/prometheus/prometheus.yml
  copy:
    src: "{{ role_path }}/files/prometheus/prometheus.yml"
    dest: /opt/stat/etc/prometheus/prometheus.yml
    owner: nobody
    group: nogroup
    mode: 0644
  tags: stat

- name: Creating /opt/stat/etc/prometheus/node.available/localhost.json
  copy:
    src: "{{ role_path }}/files/prometheus/node.available/localhost.json"
    dest: /opt/stat/etc/prometheus/node.available/localhost.json
    owner: nobody
    group: nogroup
    mode: 0644
  tags: stat

- name: Creating /opt/stat/etc/prometheus/node.available/localhost.json
  file:
    src: /opt/stat/etc/prometheus/node.available/localhost.json
    dest: /opt/stat/etc/prometheus/node.enabled/localhost.json
    state: link
  tags: stat

# Data

- name: Creating prometheus data dir
  file:
    recurse: yes
    path: /opt/stat/var/prometheus/data
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

