# roles/stat/tasks/2-prometheus-files.yml
---

# Configs

- name: "Creating /opt/stat/etc/prometheus/nodes"
  file:
    recurse: yes
    path: /opt/stat/etc/prometheus/nodes
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

- name: Check existing /opt/stat/etc/prometheus/prometheus.yml
  stat:
    path: /opt/stat/etc/prometheus/prometheus.yml
  register: st

- name: Creating /opt/stat/etc/prometheus/prometheus.yml
  copy:
    src: "{{ role_path }}/files/prometheus/prometheus.yml"
    dest: /opt/stat/etc/prometheus/prometheus.yml
  when: not st.stat.exists
  tags: stat

- name: Creating /opt/stat/etc/prometheus/nodes/host.json.example
  copy:
    src: "files/prometheus/nodes/host.json.example"
    dest: /opt/stat/etc/prometheus/nodes/host.json.example
  tags: stat

# Data

- name: Creating prometheus data dir
  file:
    recurse: yes
    path: /opt/stat/var/prometheus/data
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

