# roles/stat/tasks/4-users.yml
---

- name: Create prometheus group
  group:
    name: nogroup
    gid: 65534
    state: present
  tags: stat

- name: Create prometheus user
  user:
    name: nobody
    uid: 65534
    group: nogroup
    system: yes
    state: present
  tags: stat

- name: Create grafana group
  group:
    name: grafana
    gid: 472
    state: present
  tags: stat

- name: Create grafana user
  user:
    name: grafana
    uid: 472
    group: grafana
    system: yes
    state: present
  tags: stat
