# roles/stat/tasks/5-docker-prometheus.yml
---

- name: Creating prometheus data dir
  file:
    recurse: yes
    path: /opt/stat/var/prometheus/data
    owner: nobody
    group: nogroup
    state: directory
  tags: stat

- name: Prometheus docker container
  docker_container:
    name: stat-prometheus
    image: prom/prometheus:v{{ stat_prometheus_version }}
    volumes:
      - /opt/stat/etc/prometheus:/etc/prometheus
      - /opt/stat/var/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    state: started
    restart: yes
  tags: stat
