# roles/stat/tasks/7-docker-grafana.yml
---

- name: Creating grafana data dir
  file:
    recurse: yes
    path: /opt/stat/var/grafana/data
    owner: grafana
    group: grafana
    state: directory
  tags: stat

- name: Grafana container
  docker_container:
    name: stat-grafana
    image: grafana/grafana:{{ stat_grafana_version }}
    volumes:
      - /opt/stat/etc/grafana/provisioning:/etc/grafana/provisioning:rw
      - /opt/stat/var/grafana/data:/var/lib/grafana:rw
    ports:
      - "3000:3000"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ stat_grafana_admin_password | string }}"
      GF_USERS_ALLOW_SIGN_UP: "{{ stat_grafana_users_allow_signup | string }}"
      GF_SMTP_ENABLED: "{{ stat_grafana_smtp_enabled | string }}"
      GF_SMTP_HOST: "{{ stat_grafana_smtp_host | string }}"
      GF_SMTP_USER: "{{ stat_grafana_smtp_user | string }}"
      GF_SMTP_PASSWORD: "{{ stat_grafana_smtp_password | string }}"
      GF_SMTP_FROM_ADDRESS: "{{ stat_grafana_smtp_from_address | string }}"
      GF_SMTP_FROM_NAME: "{{ stat_grafana_smtp_from_name | string }}"
    state: started
    restart: yes
