# roles/nginx-hosts/tasks/main.yml
---

# Порядок важен!
# Сначала добавляем новый server_name в 80 хост certbot
# Дальше создаем его конфигурацию и пустую веб-директорию с индексным файлом
# После этого генерируем сертификат

- include_tasks: 1-certbot-acme-host.yml
- include_tasks: 2-virtual-hosts.yml
- include_tasks: 3-generate-cert.yml

