# roles/nginx_host/tasks/files.yml
---

- name: "Nginx host create /var/www/{{ item.name }}{{ item.public }} directory"
  file:
    path: "/var/www/{{ item.name }}{{ item.public }}"
    recurse: yes
    state: directory
    owner: nginx
    group: nginx
    mode:  0755
  with_items: "{{ nginx_hosts }}"

- name: "Nginx host add host config"
  template:
    src: https.host.conf.j2
    dest: "/etc/nginx/hosts/{{ item.name }}.conf"
    owner: root
    group: root
    mode:  0644
  with_items: "{{ nginx_hosts }}"
  notify: reload nginx

- name: "Nginx host enable config"
  file:
    src: "/etc/nginx/hosts/{{ item.name }}.conf"
    dest: "/etc/nginx/hosts.enabled/{{ item.name }}.conf"
    state: link
  with_items: "{{ nginx_hosts }}"
  notify: reload nginx
