# roles/iptables/tasks/2-rules.yml
---

- name: Flush existing firewall rules
  iptables:
    flush: true
  tags: iptables

- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: Firewall rule - allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
  tags: iptables

- name: Firewall rule - allow port 22/SSH traffic
  iptables:
    chain: INPUT
    destination_port: "22"
    jump: ACCEPT
    protocol: tcp
  tags: iptables

- name: Firewall rule - drop any traffic without rule
  iptables:
    chain: INPUT
    jump: DROP
  tags: iptables

