# roles/iptables/tasks/4-enable-service.yml
---

- name: Start service
  service:
    name: iptables
    state: started
    enabled: yes
  tags: iptables

- name: Save rules
  command: service iptables save warn=no
  become: true
  tags: iptables
