---
- hosts: dev
  become: yes

  roles:
    - role: '../roles/iptables'
    - role: '../roles/repo'
    - role: '../roles/nginx'
    - role: '../roles/php-fpm73'
    - role: '../roles/php-fpm56'
    - role: '../roles/composer'
    - role: '../roles/postgresql12'
    - role: '../roles/user-web'
    - role: '../roles/mariadb104'

  tasks:
  - name: Install tools
    yum:
      name:
        - mc
        - net-tools
        - git
        - zip
        - unzip
        - wget
      state: present
