---
- name: Install PHP 5.6
  yum:
    name:
    - php56
    - php56-php
    - php56-php-fpm
    - php56-php-pdo
    - php56-php-pgsql
    - php56-php-mysqlnd
    - php56-php-bcmath
    - php56-php-cli
    - php56-php-common
    - php56-php-gd
    - php56-php-json
    - php56-php-mbstring
    - php56-php-mcrypt
    - php56-php-pecl-imagick
    - php56-php-pecl-redis
    - php56-php-xml
    - php56-php-devel
    - php56-php-opcache
    state: present
  tags: php56

- name: Enable PHP 5.6 fpm service
  service:
    name: php56-php-fpm
    state: started
    enabled: yes
  tags: php56

- name: Install policycoreutils
  yum:
    name:
      - policycoreutils
      - policycoreutils-devel
    state: present

- name: Enable semanage php-fpm port
  seport:
    ports: 9056
    proto: tcp
    setype: http_port_t
    state: present
  tags: php56

- name: Php-fpm www.conf
  template:
    src: www.conf.j2
    dest: /etc/opt/remi/php56/php-fpm.d/www.conf
    owner: root
    group: root
    mode:  0644
  notify: restart php-fpm
  tags: php56








